version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: "host"
